---
- name: "Provisionar VM: Docker/Compose + Jenkins + Sonar + Nginx (Docker)"
  hosts: jenkins
  become: true

  vars:
    compose_dir: /opt/stack

  tasks:
    - name: "Actualizar cache de paquetes"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "Instalar dependencias base"
      apt:
        name:
          - ca-certificates
          - gnupg
          - curl
          - git
          - unzip
        state: present

    - name: "Agregar llave GPG de Docker"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Agregar repo de Docker"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: "Instalar Docker engine y plugin de Compose (v2)"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: "Agregar usuario actual al grupo docker"
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: "Asegurar vm.max_map_count (SonarQube)"
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

    - name: "Crear carpeta del stack"
      file:
        path: "{{ compose_dir }}"
        state: directory
        mode: "0755"
    
    - name: "Crear subdirectorios del stack (jenkins/nginx)"
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ compose_dir }}/jenkins"
        - "{{ compose_dir }}/nginx"

    - name: "Subir docker-compose.yml"
      copy:
        src: docker-compose.yml
        dest: "{{ compose_dir }}/docker-compose.yml"
        mode: "0644"

    - name: "Subir plugins.txt para Jenkins"
      copy:
        src: plugins.txt
        dest: "{{ compose_dir }}/jenkins/plugins.txt"
        mode: "0644"

    - name: "Subir nginx.conf"
      copy:
        src: nginx.conf
        dest: "{{ compose_dir }}/nginx/nginx.conf"
        mode: "0644"

    - name: "Levantar stack"
      shell: |
        docker compose -f {{ compose_dir }}/docker-compose.yml pull
        docker compose -f {{ compose_dir }}/docker-compose.yml up -d
      args:
        chdir: "{{ compose_dir }}"

    - name: "Instalar plugins de Jenkins desde plugins.txt"
      shell: |
        docker exec jenkins jenkins-plugin-cli --plugin-file /plugins.txt
      register: plugin_install
      changed_when: "'No changes' not in plugin_install.stdout"
      notify: restart jenkins

  handlers:
    - name: restart jenkins
      shell: docker restart jenkins